backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "/images"
collections:
- label: "Services"
  name: "services"
  folder: "content/services"
  filter: {field: "type", value: "services"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image}
    - {label: Order, name: order, widget: number, required: false}
    - {label: Content, name: body, widget: markdown}
- label: "Departments"
  name: "departments"
  folder: "content/departments"
  filter: {field: "type", value: "departments"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image}
    - {label: Order, name: order, widget: number, required: false}
    - {label: Content, name: body, widget: markdown}
- label: "Packages"
  name: "packages"
  folder: "content/packages"
  filter: {field: "type", value: "packages"}
  create: true
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Seo Title, name: seo_title, widget: string, required: false}
    - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
    - {label: Seo Description, name: seo_description, widget: text, required: false}
    - {label: Featured Image, name: featured_image, widget: image}
    - {label: Order, name: order, widget: number, required: false}
    - {label: Content, name: body, widget: markdown}        
- label: "Pages"
  name:  "pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "content/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - label: Slides
          name: slides
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: text}
            - {label: Link, name: link, widget: string}
        - {label: Content, name: body, widget: markdown}
    - label: "About"
      name: "about"
      file: "content/about/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Content, name: body, widget: markdown}
    - label: "Offer"
      name: "offer"
      file: "content/offer/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Content, name: body, widget: markdown}
    - label: "Project_Tieup"
      name: "project_tieup"
      file: "content/project_tieup/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Content, name: body, widget: markdown}             
    - label: "Gallery"
      name: "gallery"
      file: "content/gallery/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - label: Gallery
          name: gallery
          widget: list
          fields:
            - {label: Image, name: image, widget: image}
    - label: "Client"
      name: "client"
      file: "content/client/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - label: Clients
          name: clients
          widget: list
          fields:
            - {label: Image, name: image, widget: image} 
            - {label: Name, name: name, widget: string}           
    - label: "Contact Page"
      name: "contact"
      file: "content/contact/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Google Map Coordinates, name: google_map_coordinates, widget: string}
        - {label: Featured Image, name: featured_image, widget: image}
        - {label: Business Name, name: business_name, widget: string}
        - {label: Address, name: address, widget: text}
        - {label: Phone No, name: mobile, widget: string}
        - {label: Telephone No, name: phone, widget: string}
        - {label: Email, name: email, widget: string}
        - {label: Head Office, name: head_office, widget: string}
    - label: "Appointment"
      name: "appointment"
      file: "content/appointment/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Title, name: seo_title, widget: string, required: false}
        - {label: Seo Keywords, name: seo_keywords, widget: string, required: false}
        - {label: Seo Description, name: seo_description, widget: text, required: false}
        - {label: Tile_1, name: title_1, widget: string}
        - {label: description, name: description, widget: text}
        - {label: Title_2, name: title_2, widget: string}
        - {label: Email, name: email, widget: string}